export const bioText = {
    proJock: ["I honestly believe that gains are life.",
        "You can usually catch me at N.E. Thyme Gym, it's like my home away from home.",
        "Must be 6'0\" or taller, otherwise don't bother.",
        "I've been called a stallion because I'm wild, but I'd be lying if I said that's the only reason.",
        "Not looking for anything serious, I don't need any clingy types.",
        "Just looking to have some fun, not start a family.",
        "Here for a good time, not a long time.",
        "Must be a fan of rap, no exceptions.",
        "My first tattoo was \"rise and grind\" tatted on my left forearm.",
        "In the morning, the first thing I do is take my fish oil pills and wash them down with a chocolate protein shake.",
        "If that doesn't sound like you, don't even bother swiping on me.",
        "I do care about your height and your weight, but the most important number is how much you can bench.",
        "Must be okay with getting rides in my Lamborghini.",
        "Must be okay with me being the breadwinner (obviously).",
        "I never skip leg day, and neither should you.",
        "Saturdays are for the peeps."
        ],
    antiJock: ["If all you can talk about is your gains, you're probably compensating for something.",
        "I don't particularly care for abs, or the ego they bring.",
        "My ex was a gym rat, if that's you, STAY AWAY!",
        "The only thing harder to choke down than a protein shake is a conversation with those who drink ‘em.",
        "I honestly don't care to see any numbers in your bio, I'm not that shallow.",
        "If you spend more time in the gym than you do with me, we're going to have serious problems.",
        "If you were a varsity or college athlete, keep looking.",
        "Some people think being sweaty is hot. I am not one of those people.",
        "Every time you do a squat, I'm gonna take a shot.",
        "I heard people with giant muscles can't reach all of their back when they shower, that's gross."
        ],
    proFlirt: ["If you're good to me, you can call me whatever you like.",
        "You know exactly what I'm on here for.",
        "I've been told I'm pretty good at many things. Maybe you'll be lucky enough to see for yourself.",
        "If you think you can impress me, I'll give you a chance. I might reward you for your efforts.",
        "You shouldn't be able to finish anything in under a minute, except maybe unlocking your phone.",
        "The best thing about me is that I'm pretty flexible."
        ],
    antiFlirt: ["Keep it in your pants, please.",
        "I much prefer a corn dog to a horn dog.",
        "I'm looking for more than just sex, if you're not I don't want to know about it.",
        "A body count in the double digits is going to be a red flag for me.",
        "The only kind of flexibility I want to know about is in your schedule.",
        "No unsolicited pictures. Please.",
        "People who say that they're \"impressive\" in bed are usually not that impressive."
        ],
    proHumor: ["My proudest moment so far is when I convinced my 5-year-old cousin I did in fact have her nose.",
        "I usually stay up late at night crafting the perfect response to an argument I lost 5 years ago. Man, what I'd give to just go back and win that damn thing.",
        "Sometimes, late at night, I like to stand over the kitchen sink shoveling peanut butter down off a butter knife. If that sounds like a fun couple's activity, my DMs are open.",
        "I'm the best at giving birthday presence, because I always show up!",
        "I've been told I'm the life of the party. Most parties I go to are dead. I don't go to many parties, and no one has actually ever told me that.",
        "I like being the smartest person in the room. That's because it would mean I'm the only person in the room, and I'm pretty shy.",
        "Lorem ipsum dolor sit amet… haha, just kidding.",
        "Every time I hear a new knock-knock joke, I can't help but burst out into hysterical laughter. It tickles my very soul."
        ],
    antiHumor: ["Nobody wants to date a clown, seriously.",
        "If your bio is full of crappy jokes, you're not original. I promise.",
        "Don't message me just to get on the front page of ReadIt. People who do that need to grow up.",
        "This is not your audition for a stand-up gig. Please don't message me some terrible pickup line.",
        "I've been on R/grynder before. Think you're the only one with a ReadIt account?",
        "Funny people remind me of chipmunks. I'm not really looking to mess around with a chipmunk.",
        "I've never been told a joke that actually made me laugh. Don't assume you'll be the exception."
        ],
    proInt: ["There is nothing more satisfying than finally solving a tricky third order differential equation, am I right?",
        "I'm fluent in 4 languages, 13 if you include programming languages.",
        "They say the pen is mightier than the sword, but my mind is even mightier.",
        "I would bet $100 that you would never beat me in a game of Scrabbul.",
        "Please don't waste my time if your IQ is below 140.",
        "Incorrect grammar is quite literally my biggest turn-off.",
        "Did you know that the human heart beats approximately 100,000 times a day? Maybe I could make yours beat approximately 99,999 times.",
        "My hobbies include solving Roobix Cubes in under 10 seconds while blindfolded and with one hand tied behind my back, and gardening.",
        "Not to brag, but I can type 120 words per minute. 115 with my toes.",
        "I love analzying 18th century British literature, and wouldn't mind some company."],
    antiInt: ["Nerds GTFO. Don't even bother messaging me if you're a nerd.",
        "If you were picked on in High School for being a dork, you probably deserved it.",
        "It's not that I despise math, but I definitely hate it a lot.",
        "I'm looking for someone dumb and fun. Emphasis on the dumb part.",
        "There is absolutely nothing worse than a know-it-all.",
        "I would say that their is my favorite word. Like, \"Look over their!\" Just incredible.",
        "It's not a conspiracy theory if it's true! 5G towers are the enemy! Who are you going to trust, your government or me?",
        "It's like kinda crazy that birds are actually just robots sent to spy on us. Makes me scared to go outside.",
        "My favorite piece in chess is the horsey! I like that he can move forwards and backwards.",
        "I would say that anyone with a triple digit IQ is a no-go for me."],
    proSinc: ["I swear I don't get how anyone can make it through The Spiral Notebook without crying.",
        "I know why a lot of people are on here, but honestly I just want someone to cuddle with.",
        "Looking for someone whose hand fits perfectly in mine.",
        "This may sound a little cliche but I love long walks on the beach, and watching the sunset.",
        "We better be able to play Luigi Party and still be on speaking terms afterwards.",
        "I'm looking to find my soulmate, absolutely no hook-ups!",
        "It's important to me that my romantic partner is also my best friend.",
        "My passion is helping others.",
        "I'm a creative type.",
        "My biggest monthly expense is giving to charity.",
        "You can often find me with my large caramel macchiato with almond milk, 2 pumps of vanilla, one shot, and light whip on top at a local CupO'Java.",
        "Always looking to pay it forward.",
        "Always giving back to those in need.",
        "I just wish I could hug everyone who needs a hug."],
    antiSinc: ["I can not STAND sappy people.",
        "Please don't even contact me if you've ever cried during The Spiral Notebook.",
        "Nice folk finish last, what can I say?",
        "I absolutely would never be caught dead taking a stroll on the beach.",
        "I've heard watching the sunset can cause retinal damage.",
        "People who need to brag about \"giving back\" are sick.",
        "If you want to find true love, why are you on this site?",
        "Only willing to cuddle after you satisfy my needs.",
        "I don't need to hear about how your day went. We're not friends, we're friends with benefits.",
        "The only thing I hate more than emotional wrecks is poetry. Yuck."
        ]
}

export const schoolText = {
    major: ["Basket Weaving", "Wine Tasting", "Reusable Bag Engineering", "Hand Modeling", "Blind Taste Testing", "Quilt Engineering", "Guitar Tuning", "Russian Chess Studies", "Vegan Studies", "Shampoo and Conditioner Engineering", "Esports management"],
    school: ["Quinoa University", "Millet Institute of Learning", "Buckwheat College", "Brown Rice University", "Couscous College", "Gemelli Institute of Knowledge", "Linguini State University", "UC Barley", "SUNY Orzo"]
}

export const employeeText = {
    job: ["Product Manager", "Shift Supervisor", "Professional Picture Framer", "Reverse Osmosis Engineer", "Hydrochloric Acid Administrator", "Professional Glass Blower", "CEO", "Renowned Pep Rally Emcee", "Customer Service Representative", "Lead Lint Roller", "Associate Furniture Assembler"],
    company: ["FootLetter", "Quintillion", "Grey Beans", "Walrus", "Sherp & Co.", "Tori's Furniture and Meatball Factory", "NiceHome", "Books4Chumps.org", "CupO'Java", "Samuel M.L. and Sons", "GreatPurchase", "InternetRetail.com", "ShoeTube"]
}