export const SkillText = {
    sf: {effect: "Weaker Pinks", tooltip: "I like the ladies"},
    sf1: {effect: "Player Spd+", tooltip: "I just care about moving quickly"},
    sf11: {effect: "Player Spd++", tooltip: "Gotta go fast"},
    sf12: {effect: "Active Invis", tooltip: "I'm a silent, thought-ful type"},
    sf2: {effect: "Bullet Spd+", tooltip: "Communiction is key"},
    sf21: {effect: "Bullet Spd++", tooltip: "I'm kind and truthul"},
    sf22: {effect: "Bullets Stun", tooltip: "Back- handed comp- lements"},
    sm: {effect: "Weaker Blues", tooltip: "Boys, boys, boys!"},
    sm1: {effect: "Bullet Pwr+", tooltip: "It's how you use it"},
    sm11: {effect: "Bullet Pwr++", tooltip: "I give love and support"},
    sm12: {effect: "Piercing Bullets", tooltip: "I'm a heart breaker"},
    sm2: {effect: "Bullet Size+", tooltip: "Size matters"},
    sm21: {effect: "Bullet Size++", tooltip: "Vanilla is best"},
    sm22: {effect: "Shoot 2 Bullets", tooltip: "I'm down for stuff"},
    sb: {effect: "Weaker Purples", tooltip: "If it fits, it ships"},
    sb1: {effect: "Big Enemies", tooltip: "I like 'em thicc"},
    sb11: {effect: "Slower Enemies", tooltip: "I like to take it slow"},
    sb12: {effect: "Active Freeze", tooltip: "I need a break"},
    sb2: {effect: "Small Enemies", tooltip: "I like 'em thinn"},
    sb21: {effect: "Random Enemy Death", tooltip: "Everyone falls for me"},
    sb22: {effect: "Active AOE Kill", tooltip: "I tend to push people away"},
}